site_name: Senior Engineering - Kanofsky
site_url: https://ckanofskyschool.github.io/Kanofsky-Collin-Portfolio/
site_description: Senior Engineering at Charlotte Latin School
site_author: Collin Kanofsky

theme:
  name: shadcn

nav:
  - Home: index.md
  - Daily Journal: DailyJournal.md
  - Project Overview: ProjectOverview.md
  - Robot Planning: RobotPlanning.md
  - Robot Journey: RobotJourney.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption